const mongoose = require('mongoose');

/**
 * AI Insight Schema
 * Stores the responses generated by the AI model.
 */
const aiInsightSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      required: true,
      enum: ['promotion', 'ranking', 'training', 'feedback'],
    },
    content: {
      type: String,
      required: true,
    },
    analyzedEmployees: {
      type: [String],
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model('AIInsight', aiInsightSchema);
